### PR TITLE
Root link in menu configurable

### PR DESCRIPTION
**Pull request by cfchou**
This PR is for #5.

I add Params.rootlink for that purpose. Extracted from updated README:
```
baseurl = "http://your-site.com/blog"
languageCode = "en-US"
title = "Your site"
theme = "code-editor"

[params]
    author = "John Doe"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to.
    # 1. If it's not set than baseurl will be used.
    # 2. If it's set to a url(w/ a scheme), like rootlink="https://www.google.com",
    #    then Root will link to https://www.google.com.
    # 3. If it's set to a path(w/o a scheme), like rootlink="doc", then Root
    #    will link to an url concatenated by host in baseurl and rootlink. In
    #    this case, it comes up with http://your-site.com/doc.
```

### CODE REVIEW

**Comment by aubm** [comment]
Hello @cfchou, thank you for the PR :)
It seems that the third option specified in the README.md doesn't work.
Do you mind implementing it or removing it from the README.md?

**Comment by cfchou** [comment]
Thanks @aubm for your work. I like this theme a lot.

It's strange that the 3rd doesn't work for you. I tested it and it worked on my site hosted on localhost/github/bitbucket. Maybe we're using different versions of hugo? 

> $ hugo version
> Hugo Static Site Generator v0.24.1 darwin/amd64 BuildDate: 2017-06-28T21:12:16+08:00

I'm not sure why it's not working . But I guess one could always resort to the 2ed option(although a bit annoying when working on local dev). So I'll remove the 3rd from README later.

**Comment by aubm** [comment]
Good point, the build of Hugo that I have is quite old, let me double check with the latest one.

**Comment by aubm** [comment]
I just tried again with the latest version, and it still does not work :(

```
Hugo Static Site Generator v0.25-DEV darwin/amd64 BuildDate: 2017-07-01T09:09:59+02:00
```

I must say that, based on what I understand from the code change, that makes sense.

```
index .Site.Params "rootlink" | default .Site.BaseURL
```

Reading: print the index "rootlink" of the .Site.Params map (without applying any kind of transformation), or print the site base url if the latter does not exist

Nevertheless if I serve the site locally with a relative path set for `rootlink`- like in the example: `rootlink="doc"` - the browser correctly links to `http://localhost:1313/doc`. But the HTML code generated by Hugo is `<a href="doc">...</a>`.

So maybe it does work the way you expect it to work, but the statement `then Root will link to an url concatenated by host in baseurl and rootlink` is misleading, because it is the browser that actually does that. Maybe something like `then Root will link to "doc", which should work fine in the browser too` would better describe the behavior?

Sorry to bother you with the detail :)

**Comment by cfchou** [comment]
Thank you for all the detail. I found the same problem too after reading the generated html. You're right that Hugo passes on the variable verbatim and actually it's the browser to point to the right place. I'll follow your advise to update README.

**Comment by cfchou** [comment]
On second thought, maybe it only needs to be said in README that baseurl will be used if params.rootlink is not set(i.e. the 1st point). Because if rootlink is set then Hugo simply passes it on to the generated html, be it a full address or just a path. What do you think?

**Comment by aubm** [comment]
Yep, I agree :)

**Comment by aubm** [comment]
Hey @cfchou thanks for the update.

One last thing before I can merge your work: is there any particular reason for the baseUrl to have been changed in the README? If not maybe it would be better to revert that change.

PS: I think there is a little typo in the sentence "If it's not set **than** baseurl will be used"

**Comment by cfchou** [comment]
No problem. I have committed the change.

**Comment by aubm** [comment]
Thank you :)

**Pull request merged**
